/*
 Piwik - free/libre analytics platform

 JavaScript tracking client

 @link http://piwik.org
 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license http://piwik.org/free-software/bsd/ BSD-3 Clause (also in ./LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
 @license-end */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(l,h,m){l instanceof String&&(l=String(l));for(var u=l.length,p=0;p<u;p++){var G=l[p];if(h.call(m,G,p,l))return{i:p,v:G}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,h,m){if(l==Array.prototype||l==Object.prototype)return l;l[h]=m.value;return l};$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var h=0;h<l.length;++h){var m=l[h];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,h){var m=$jscomp.propertyToPolyfillSymbol[h];if(null==m)return l[h];m=l[m];return void 0!==m?m:l[h]};
$jscomp.polyfill=function(l,h,m,u){h&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,h,m,u):$jscomp.polyfillUnisolated(l,h,m,u))};$jscomp.polyfillUnisolated=function(l,h,m,u){m=$jscomp.global;l=l.split(".");for(u=0;u<l.length-1;u++){var p=l[u];if(!(p in m))return;m=m[p]}l=l[l.length-1];u=m[l];h=h(u);h!=u&&null!=h&&$jscomp.defineProperty(m,l,{configurable:!0,writable:!0,value:h})};
$jscomp.polyfillIsolated=function(l,h,m,u){var p=l.split(".");l=1===p.length;u=p[0];u=!l&&u in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var G=0;G<p.length-1;G++){var B=p[G];if(!(B in u))return;u=u[B]}p=p[p.length-1];m=$jscomp.IS_SYMBOL_NATIVE&&"es6"===m?u[p]:null;h=h(m);null!=h&&(l?$jscomp.defineProperty($jscomp.polyfills,p,{configurable:!0,writable:!0,value:h}):h!==m&&(void 0===$jscomp.propertyToPolyfillSymbol[p]&&(m=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[p]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(p):$jscomp.POLYFILL_PREFIX+m+"$"+p),$jscomp.defineProperty(u,$jscomp.propertyToPolyfillSymbol[p],{configurable:!0,writable:!0,value:h})))};$jscomp.polyfill("Array.prototype.find",function(l){return l?l:function(h,m){return $jscomp.findInternal(this,h,m).v}},"es6","es3");
$jscomp.checkStringArgs=function(l,h,m){if(null==l)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return l+""};
$jscomp.polyfill("String.prototype.endsWith",function(l){return l?l:function(h,m){var u=$jscomp.checkStringArgs(this,h,"endsWith");h+="";void 0===m&&(m=u.length);m=Math.max(0,Math.min(m|0,u.length));for(var p=h.length;0<p&&0<m;)if(u[--m]!=h[--p])return!1;return 0>=p}},"es6","es3");
Array.prototype.forEach||(Array.prototype.forEach=function(l,h){var m;if(null==this)throw new TypeError(" this is null or not defined");var u=Object(this),p=u.length>>>0;if("[object Function]"!={}.toString.call(l))throw new TypeError(l+" is not a function");h&&(m=h);for(h=0;h<p;){if(h in u){var G=u[h];l.call(m,G,h,u)}h++}});
var searchIntervalId=searchIntervalId||0,searchIntervalCount=searchIntervalId||0,DcmAn={addListener:function(l,h,m){l.addEventListener?l.addEventListener(h,m,{passive:!0}):l.attachEvent&&l.attachEvent("on"+h,m)},addFormEvent:function(){var l=document.getElementsByTagName("form");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"submit",DcmAn.decorateMe)},addEvent:function(){var l=document.getElementsByTagName("a");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"mousedown",DcmAn.decorateMe),DcmAn.addListener(l[i],
"keyup",DcmAn.decorateMe),DcmAn.addListener(l[i],"touchstart",DcmAn.decorateMe)},decorateMe:function(l){l=l||window.event;if((l=l.target||l.srcElement)&&l.href)DcmAn.checkDomain(l.href)&&(l.href=DcmAn.decorateDmpfCross(l.href));else if(l&&l.action&&DcmAn.checkDomain(l.action))if("get"==l.method){var h=DcmAn.getDaCookieId();if(1<h.length){var m=document.createElement("input");m.type="hidden";m.name="dcmancr";m.value=DcmAn.makeCrossParam(h);l.appendChild(m)}}else l.action=DcmAn.decorateDmpfCross(l.action)},
checkDomain:function(l){var h=!1;_dcmlinker.forEach(function(m){var u=l.match(/^https?:\/\/([^\/:]+)/);null!=u&&u[1]==m&&(h=!0)});return h},decorateDmpfCross:function(l){var h=DcmAn.getDaCookieId();if(1<h.length){var m=l.split("#");l=m[0];h=DcmAn.makeCrossParam(h);var u=l.split("?");if(1==u.length)l=l+"?dcmancr="+h;else{u=u[1].split("&");var p=!0;for(i=0;i<u.length;i++)if(0==u[i].indexOf("dcmancr=")){p=!1;break}p&&(l=l+"&dcmancr="+h)}1<m.length&&(l=l+"#"+m[1])}return l},makeCrossParam:function(l){for(var h=
l.length,m=0,u=(new Date).getTime(),p=0;p<h;p++)m+=l.charCodeAt(p);h=DcmAn.getGaCookieId();p=DcmAn.makeUa();return l+"."+u+"."+p+"."+(m+u+p)+(h?"_"+h+"_"+Piwik.getAsyncTracker().getSiteId():"")},getDaCookieId:function(){if(window.navigator.cookieEnabled&&document.cookie)for(var l=document.cookie.split("; "),h=0;h<l.length;h++){var m=l[h].split("=");if("daxtr"==m[0])return m[1].split(".")[0]}return""},getGaCookieId:function(){if(window.navigator.cookieEnabled&&document.cookie){var l=/(^|;)[ ]*_ga=([^;]*)/.exec(document.cookie);
if((l=l?l[2]:"")&&l.match(/.*\.\d+\.(\d+\.\d+)/))return RegExp.$1}return 0},makeUa:function(){for(var l=navigator.userAgent.length,h=0,m=0;m<l;m++)h+=navigator.userAgent.charCodeAt(m);return h}};"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function l(y){if("undefined"!=typeof window.addEventListener){var H=document.readyState;"interactive"==H||"complete"==H||"loaded"==H?y():document.addEventListener("DOMContentLoaded",y,!1)}else"undefined"!=typeof window.attachEvent&&(window.attachEvent("onload",y),y())}function h(y){return 10>y?"0"+y:y}function m(y){ja.lastIndex=0;return ja.test(y)?'"'+y.replace(ja,function(H){var S=Wa[H];return"string"===typeof S?S:"\\u"+("0000"+H.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+y+'"'}
function u(y,H){var S=T,z=H[y];if(z&&"object"===typeof z){var ba=Object.prototype.toString.apply(z);z="[object Date]"===ba?isFinite(z.valueOf())?z.getUTCFullYear()+"-"+h(z.getUTCMonth()+1)+"-"+h(z.getUTCDate())+"T"+h(z.getUTCHours())+":"+h(z.getUTCMinutes())+":"+h(z.getUTCSeconds())+"Z":null:"[object String]"===ba||"[object Number]"===ba||"[object Boolean]"===ba?z.valueOf():"[object Array]"!==ba&&"function"===typeof z.toJSON?z.toJSON(y):z}"function"===typeof X&&(z=X.call(H,y,z));switch(typeof z){case "string":return m(z);
case "number":return isFinite(z)?String(z):"null";case "boolean":case "null":return String(z);case "object":if(!z)return"null";T+=Ga;var Q=[];if("[object Array]"===Object.prototype.toString.apply(z)){ba=z.length;for(y=0;y<ba;y+=1)Q[y]=u(y,z)||"null";H=0===Q.length?"[]":T?"[\n"+T+Q.join(",\n"+T)+"\n"+S+"]":"["+Q.join(",")+"]";T=S;return H}if(X&&"object"===typeof X)for(ba=X.length,y=0;y<ba;y+=1){if("string"===typeof X[y]){var M=X[y];(H=u(M,z))&&Q.push(m(M)+(T?": ":":")+H)}}else for(M in z)Object.prototype.hasOwnProperty.call(z,
M)&&(H=u(M,z))&&Q.push(m(M)+(T?": ":":")+H);H=0===Q.length?"{}":T?"{\n"+T+Q.join(",\n"+T)+"\n"+S+"}":"{"+Q.join(",")+"}";T=S;return H}}l(DcmAn.addEvent);l(DcmAn.addFormEvent);var p="",G=location.href,B=G.split("?dcmancr=");2==B.length?p=-1!=B[1].indexOf("&")?B[1].split("&")[0]:B[1]:(B=G.split("&dcmancr="),2==B.length&&(p=-1!=B[1].indexOf("&")?B[1].split("&")[0]:B[1]));0<p.length&&12E4>(new Date).getTime()-p.split(".")[1]&&(p=p.split("_"),_paq.unshift(["appendToTrackingUrl","dcmancr="+p[0]]));"use strict";
var ka=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,ja=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,T,Ga,Wa={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},X;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(y,H,S){var z;Ga=T="";if("number"===typeof S)for(z=0;z<S;z+=1)Ga+=" ";else"string"===typeof S&&(Ga=S);if((X=
H)&&"function"!==typeof H&&("object"!==typeof H||"number"!==typeof H.length))throw Error("JSON2.stringify");return u("",{"":y})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(y,H){function S(z,ba){var Q,M=z[ba];if(M&&"object"===typeof M)for(Q in M)if(Object.prototype.hasOwnProperty.call(M,Q)){var Ma=S(M,Q);void 0!==Ma?M[Q]=Ma:delete M[Q]}return H.call(z,ba,M)}y=String(y);ka.lastIndex=0;ka.test(y)&&(y=y.replace(ka,function(z){return"\\u"+("0000"+z.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(y.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return y=eval("("+y+")"),"function"===typeof H?S({"":y},""):y;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function l(b){try{return kb(b)}catch(e){return unescape(b)}}function h(b){return"undefined"!==typeof b}function m(b){return"function"===typeof b}function u(b){return"object"===typeof b}function p(b){return"string"===typeof b||b instanceof String}function G(){var b;for(b=0;b<arguments.length;b+=1){var e=arguments[b];var g=e.shift();p(g)?Xa[g].apply(Xa,e):g.apply(Xa,e)}}function B(b,e,g,k){if(b.addEventListener)return b.addEventListener(e,g,k),!0;if(b.attachEvent)return b.attachEvent("on"+
e,g);b["on"+e]=g}function ka(b,e){var g="",k;for(k in Na)if(Object.prototype.hasOwnProperty.call(Na,k)){var q=Na[k][b];m(q)&&(g+=q(e))}return g}function ja(){var b;if(!Oa)for(Oa=!0,ka("load"),b=0;b<lb.length;b++)lb[b]();return!0}function T(b,e){var g=v.createElement("script");g.type="text/javascript";g.src=b;g.readyState?g.onreadystatechange=function(){var k=this.readyState;if("loaded"===k||"complete"===k)g.onreadystatechange=null,e()}:g.onload=e;v.getElementsByTagName("head")[0].appendChild(g)}function Ga(){var b=
"";try{b=w.top.document.referrer}catch(e){if(w.parent)try{b=w.parent.document.referrer}catch(g){b=""}}""===b&&(b=v.referrer);return b}function Wa(b){return(b=/^([a-z]+):/.exec(b))?b[1]:null}function X(b){var e=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b);return e?e[1]:b}function y(b,e){return(b=(new RegExp("[\\?&#]"+e+"=([^&#]*)")).exec(b))?kb(b[1]):""}function H(b){var e=function(Aa,la){return Aa<<la|Aa>>>32-la},g=function(Aa){var la="",ta;for(ta=7;0<=ta;ta--){var ua=Aa>>>4*ta&15;la+=ua.toString(16)}return la},
k,q=[],P=1732584193,N=4023233417,O=2562383102,Y=271733878,ea=3285377520,D=[];b=rc(C(b));var A=b.length;for(k=0;k<A-3;k+=4){var I=b.charCodeAt(k)<<24|b.charCodeAt(k+1)<<16|b.charCodeAt(k+2)<<8|b.charCodeAt(k+3);D.push(I)}switch(A&3){case 0:k=2147483648;break;case 1:k=b.charCodeAt(A-1)<<24|8388608;break;case 2:k=b.charCodeAt(A-2)<<24|b.charCodeAt(A-1)<<16|32768;break;case 3:k=b.charCodeAt(A-3)<<24|b.charCodeAt(A-2)<<16|b.charCodeAt(A-1)<<8|128}for(D.push(k);14!==(D.length&15);)D.push(0);D.push(A>>>
29);D.push(A<<3&4294967295);for(b=0;b<D.length;b+=16){for(k=0;16>k;k++)q[k]=D[b+k];for(k=16;79>=k;k++)q[k]=e(q[k-3]^q[k-8]^q[k-14]^q[k-16],1);I=P;A=N;var U=O;var R=Y;var fa=ea;for(k=0;19>=k;k++){var K=e(I,5)+(A&U|~A&R)+fa+q[k]+1518500249&4294967295;fa=R;R=U;U=e(A,30);A=I;I=K}for(k=20;39>=k;k++)K=e(I,5)+(A^U^R)+fa+q[k]+1859775393&4294967295,fa=R,R=U,U=e(A,30),A=I,I=K;for(k=40;59>=k;k++)K=e(I,5)+(A&U|A&R|U&R)+fa+q[k]+2400959708&4294967295,fa=R,R=U,U=e(A,30),A=I,I=K;for(k=60;79>=k;k++)K=e(I,5)+(A^U^
R)+fa+q[k]+3395469782&4294967295,fa=R,R=U,U=e(A,30),A=I,I=K;P=P+I&4294967295;N=N+A&4294967295;O=O+U&4294967295;Y=Y+R&4294967295;ea=ea+fa&4294967295}K=g(P)+g(N)+g(O)+g(Y)+g(ea);return K.toLowerCase()}function S(b,e,g){if("translate.googleusercontent.com"===b)""===g&&(g=e),e=y(e,"u"),b=X(e);else if("cc.bingj.com"===b||"webcache.googleusercontent.com"===b||"74.6."===b.slice(0,5))e=v.links[0].href,b=X(e);return[b,e,g]}function z(b){var e=b.length;"."===b.charAt(--e)&&(b=b.slice(0,e));"*."===b.slice(0,
2)&&(b=b.slice(1));return b}function ba(b){b=b&&b.text?b.text:b;if(!p(b)){var e=v.getElementsByTagName("title");e&&h(e[0])&&(b=e[0].text)}return b}function Q(b){return b?!h(b.children)&&h(b.childNodes)||h(b.children)?b.children:[]:[]}function M(b,e){if(b&&b.indexOf)return b.indexOf(e);if(!h(b)||null===b||!b.length)return-1;var g=b.length;if(0===g)return-1;for(var k=0;k<g;){if(b[k]===e)return k;k++}return-1}function Ma(b){function e(k,q){if(w.getComputedStyle)return v.defaultView.getComputedStyle(k,
null)[q];if(k.currentStyle)return k.currentStyle[q]}function g(k,q,P,N,O,Y,ea){var D=k.parentNode,A;a:{for(A=k.parentNode;A;){if(A===v){A=!0;break a}A=A.parentNode}A=!1}if(!A)return!1;if(9===D.nodeType)return!0;if("0"===e(k,"opacity")||"none"===e(k,"display")||"hidden"===e(k,"visibility"))return!1;h(q)&&h(P)&&h(N)&&h(O)&&h(Y)&&h(ea)||(q=k.offsetTop,O=k.offsetLeft,N=q+k.offsetHeight,P=O+k.offsetWidth,Y=k.offsetWidth,ea=k.offsetHeight);if(b===k&&(0===ea||0===Y)&&"hidden"===e(k,"overflow"))return!1;
if(D){if("hidden"===e(D,"overflow")||"scroll"===e(D,"overflow"))if(O+1>D.offsetWidth+D.scrollLeft||O+Y-1<D.scrollLeft||q+1>D.offsetHeight+D.scrollTop||q+ea-1<D.scrollTop)return!1;k.offsetParent===D&&(O+=D.offsetLeft,q+=D.offsetTop);return g(D,q,P,N,O,Y,ea)}return!0}return b?g(b):!1}function sc(b,e){if(e)return e;"piwik.php"===b.slice(-9)&&(b=b.slice(0,b.length-9));return b}function Ba(b){var e=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(v.referrer);
if(e){if(e[1]!==String(b))return!1;w.name="Piwik_Overlay###"+e[2]+"###"+e[3]}b=w.name.split("###");return 3===b.length&&"Piwik_Overlay"===b[0]}function tc(b,e,g){var k=w.name.split("###"),q=k[1],P=k[2],N=sc(b,e);T(N+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(N,g,q,P)})}function Ib(b,e){function g(a,c,d,f,n,r){if(!va){if(d){var x=new Date;x.setTime(x.getTime()+d)}if(n)v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+(r?";secure":"");else{var L=
document.domain;if(L.endsWith(".docomo.ne.jp"))document.domain.split("."),v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+";domain=.docomo.ne.jp"+(r?";secure":"");else{var E=document.domain.split("."),J=E.length,ma=!1;n="."+E[J-1];for(var Z=J-2;0<=Z;Z--){if(Z==J-2&&L.endsWith(".co.jp")||L.endsWith(".ne.jp")||L.endsWith(".or.jp")||L.endsWith(".ac.jp")||L.endsWith(".ad.jp")||L.endsWith(".ed.jp")||L.endsWith(".go.jp")||L.endsWith(".gr.jp")||L.endsWith(".lg.jp"))n="."+E[Z]+n,
Z--;n="."+E[Z]+n;v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+";domain="+n+(r?";secure":"");for(var Ca=document.cookie.split(";"),na=0;na<Ca.length;na++)if(Ca[na].split("=")[0].trim()==a){ma=!0;break}if(ma)break}}}}}function k(a){return va?0:(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(v.cookie))?kb(a[2]):0}function q(a){if(Jb){var c=/#.*/;return a.replace(c,"")}return a}function P(a){var c;for(c=0;c<Ya.length;c++){var d=z(Ya[c].toLowerCase());if(a===d)return!0;if("."===
d.slice(0,1)){if(a===d.slice(1))return!0;var f=a.length-d.length;if(0<f&&a.slice(f)===d)return!0}}return!1}function N(a,c){c=!0;a=ha+(0>ha.indexOf("?")?"?":"&")+a;var d=Ha("daReqProb");if(null==d||0==(new Date).getTime()%d)null!=Ha("afterAuthFlg")&&(a+="&afterAuthFlg=1"),1==Ha("trackingType")?null!=Ha("afterAuthFlg")?(a+="&trackingType=1",(new Date).getTime(),d=mb+"_dcmsend",0===k(d)?g(d,1,4752E5,"/"):c=!1):c=!1:2==Ha("trackingType")&&(a+="&trackingType=2"),c&&(c=document.createElement("img"),c.setAttribute("src",
a),c.style.display="none",document.body.appendChild(c))}function O(a,c,d){h(d)&&null!==d||(d=!0);try{var f=w.XMLHttpRequest?new w.XMLHttpRequest:w.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;f.open("POST",ha,!0);f.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!d?"function"===typeof c&&c():N(a,c)};f.setRequestHeader("Content-Type",Kb);f.send(a)}catch(n){d&&N(a,c)}}function Y(a){a=(new Date).getTime()+a;if(!Pa||a>Pa)Pa=a}function ea(a){var c=(new Date).getTime();
Ia&&c<Ia?(c=Ia-c,setTimeout(a,c),Y(c+50),Ia+=50):(!1===Ia&&(Ia=c+800),a())}function D(a,c,d){!Za&&a&&ea(function(){"POST"===Lb?O(a,d):N(a,d);Y(c)})}function A(a,c){var d=Za?!1:a&&a.length;if(d){var f='{"requests":["?'+a.join('","?')+'"]}';ea(function(){O(f,null,!1);Y(c)})}}function I(a){return mb+a+"."+W+"."+Mb}function U(){if(va)return"0";if(!h(ca.cookieEnabled)){var a=I("testcookie");g(a,"1");return"1"===k(a)?"1":"0"}return ca.cookieEnabled?"1":"0"}function R(){Mb=nb((Da||ob)+(wa||"/")).slice(0,
4)}function fa(){var a=I("cvar");a=k(a);return a.length&&(a=JSON2.parse(a),u(a))?a:{}}function K(){pb=(new Date).getTime()}function Aa(){var a=Math.round((new Date).getTime()/1E3),c=k("daxtr");return c?(a=c.split("."),a.unshift("0"),Qa.length&&(a[1]=Qa),a):a=["1",Qa.length?Qa:"0"===U()?"":nb((ca.userAgent||"")+(ca.platform||"")+JSON2.stringify(qa)+(new Date).getTime()+Math.random()).slice(0,32),a,0,a,"",""]}function la(){var a=Aa(),c=a[0],d=a[1],f=a[2]?a[2]:a[4],n=a[3]?a[3]:1,r=a[4],x="undefined"==
a[5]||""==a[5]?a[4]:a[5];h(a[6])||(a[6]="");return{newVisitor:c,uuid:d,createTs:f,visitCount:n,currentVisitTs:r,lastVisitTs:x,lastEcommerceOrderTs:a[6]}}function ta(a){W&&((new Date).getTime(),h(a)||(a=la()),g("daxtr",a.uuid+"."+a.createTs+".",339552E5,wa))}function ua(){var a=k(I("ref"));if(a.length)try{if(a=JSON2.parse(a),u(a))return a}catch(c){}return["","",0,""]}function Nb(){var a=va;va=!1;g("daxtr","",-86400,wa,Da);var c=I("ses");g(c,"",-86400,wa,Da);c=I("cvar");g(c,"",-86400,wa,Da);c=I("ref");
g(c,"",-86400,wa,Da);va=a}function Ob(a){if(a&&u(a)){var c=[];for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&c.push(d);var d={};c.sort();var f=c.length,n;for(n=0;n<f;n++)d[c[n]]=a[c[n]];return d}}function oa(a,c,d,f){function n($a,uc){$a=JSON2.stringify($a);return 2<$a.length?"&"+uc+"="+C($a):""}var r=new Date,x=Math.round(r.getTime()/1E3),L=da,E=I("ses");I("ref");var J=I("cvar");var ma=k(E);var Z=ua();var Ca=ab||Pb;va&&Nb();if(Za)return"";E=la();h(f)||(f="");var na={};var ra=location.search.substring(1).split("&");
for(f=0;ra[f];f++){var sa=ra[f].split("=");na[sa[0]]=sa[1]}na.dcmancr&&(E.uuid=na.dcmancr.split(".")[0]);var Ra=v.characterSet||v.charset;Ra&&"utf-8"!==Ra.toLowerCase()||(Ra=null);sa=Z[0];var Sa=Z[1];na=Z[2];ra=Z[3];if(!ma){ma=qb/1E3;if(!E.lastVisitTs||x-E.lastVisitTs>ma)E.visitCount++,E.lastVisitTs=E.currentVisitTs;if(!rb||!sa.length){for(f in bb)if(Object.prototype.hasOwnProperty.call(bb,f)&&(sa=y(Ca,bb[f]),sa.length))break;for(f in cb)if(Object.prototype.hasOwnProperty.call(cb,f)&&(Sa=y(Ca,cb[f]),
Sa.length))break}ma=X(Ea);Z=ra.length?X(ra):"";!ma.length||P(ma)||rb&&Z.length&&!P(Z)||(ra=Ea);if(ra.length||sa.length)na=x,Z=[sa,Sa,na,q(ra.slice(0,1024))]}x=!1;1===Ha("trackingType")&&(x=!0);if(x)a="idsite="+W+"&url="+C(q(Ca))+(Ea.length?"&urlref="+C(q(Ea)):"")+"&_id2="+E.uuid;else{a+="&idsite="+W+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+r.getHours()+"&m="+r.getMinutes()+"&s="+r.getSeconds()+"&url="+C(q(Ca))+(Ea.length?"&urlref="+C(q(Ea)):"")+(Ja&&Ja.length?"&uid="+C(Ja):"")+"&_idts="+
E.createTs+"&_idvc="+E.visitCount+"&_id2="+E.uuid+"&_idn="+E.newVisitor+(sa.length?"&_rcn="+C(sa):"")+(Sa.length?"&_rck="+C(Sa):"")+"&_refts="+na+"&_viewts="+E.lastVisitTs+(String(E.lastEcommerceOrderTs).length?"&_ects="+E.lastEcommerceOrderTs:"")+(String(ra).length?"&_ref="+C(q(ra.slice(0,1024))):"")+(Ra?"&cs="+C(Ra):"")+"&send_image=0";for(f in qa)Object.prototype.hasOwnProperty.call(qa,f)&&(a+="&"+f+"="+qa[f]);c?a+="&data="+C(JSON2.stringify(c)):xa&&(a+="&data="+C(JSON2.stringify(xa)));c=Ob(Fa);
r=Ob(sb);a+=n(c,"cvar");a+=n(r,"e_cvar");if(da){a+=n(da,"_cvar");for(f in L)Object.prototype.hasOwnProperty.call(L,f)&&(""===da[f][0]||""===da[f][1])&&delete da[f];Qb&&g(J,JSON2.stringify(da),qb,wa,Da)}Rb&&(tb?a+="&gt_ms="+tb:Ka&&Ka.timing&&Ka.timing.requestStart&&Ka.timing.responseEnd&&(a+="&gt_ms="+(Ka.timing.responseEnd-Ka.timing.requestStart)))}ta(E);a+=ka(d);ub.length&&(a+="&"+ub);m(vb)&&(a=vb(a));if(window.navigator.cookieEnabled&&document.cookie)for(d=document.cookie.split("; "),f=0;f<d.length;f++)d[f].split("=")[0].split(".");
return a}function Sb(a,c,d,f,n,r){var x="idgoal=0",L=new Date,E=[],J;if(String(a).length){x+="&ec_id="+C(a);var ma=Math.round(L.getTime()/1E3)}x+="&revenue="+c;String(d).length&&(x+="&ec_st="+d);String(f).length&&(x+="&ec_tx="+f);String(n).length&&(x+="&ec_sh="+n);String(r).length&&(x+="&ec_dt="+r);if(aa){for(J in aa)Object.prototype.hasOwnProperty.call(aa,J)&&(h(aa[J][1])||(aa[J][1]=""),h(aa[J][2])||(aa[J][2]=""),h(aa[J][3])&&0!==String(aa[J][3]).length||(aa[J][3]=0),h(aa[J][4])&&0!==String(aa[J][4]).length||
(aa[J][4]=1),E.push(aa[J]));x+="&ec_items="+C(JSON2.stringify(E))}x=oa(x,xa,"ecommerce",ma);D(x,V)}function vc(a,c){var d=new Date;a=oa("action_name="+C(ba(a||Tb)),c,"log");D(a,V);wb&&Ta&&!Ub&&(Ub=!0,B(v,"click",K),B(v,"mouseup",K),B(v,"mousedown",K),B(v,"mousemove",K),B(v,"mousewheel",K),B(w,"DOMMouseScroll",K),B(w,"scroll",K),B(v,"keypress",K),B(v,"keydown",K),B(v,"keyup",K),B(w,"resize",K),B(w,"focus",K),B(w,"blur",K),pb=d.getTime(),setTimeout(function n(){d=new Date;if(pb+Ta>d.getTime()){if(wb<
d.getTime()){var r=oa("ping=1",c,"ping");D(r,V)}setTimeout(n,Ta)}},Ta))}function xb(a,c){var d="(^| )(piwik[_-]"+c;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return new RegExp(d+")( |$)")}function Ua(a){return ha&&a&&0===String(a).indexOf(ha)}function yb(a){var c=a,d;for(d=c.parentNode;null!==d&&h(d)&&!t.isLinkElement(c);)c=d,d=c.parentNode;a=c;if(t.hasNodeAttribute(a,"href")&&h(a.href)&&(c=t.getAttributeValueFromNode(a,"href"),!Ua(c))){c=a.hostname||X(a.href);var f=c.toLowerCase();c=a.href.replace(c,
f);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(c)){d=a.className;f=P(f);a=t.hasNodeAttribute(a,"download");if(Ua(c))d=0;else{var n=xb(Vb,"download"),r=xb(Wb,"link"),x=new RegExp("\\.("+ya.join("|")+")([?&#]|$)","i");d=r.test(d)?"link":a||n.test(d)||x.test(c)?"download":f?0:"link"}if(d)return{type:d,href:c}}}}function Va(a,c,d,f){if(a=F.buildInteractionRequestParams(a,c,d,f))return oa(a,null,"contentInteraction")}function Xb(a,c,d,f,n){if(h(a)){if(Ua(a))return a;
var r=F.toAbsoluteUrl(a);r="redirecturl="+C(r)+"&";r+=Va(c,d,f,n||a);a="&";0>ha.indexOf("?")&&(a="?");return ha+a+r}}function zb(a,c){if(!a||!c)return!1;var d=F.findTargetNode(a);if(F.shouldIgnoreInteraction(d))return!1;if(a=d=F.findTargetNodeNoDefault(a))a=!(d&&c&&(d.contains?d.contains(c):d===c||d.compareDocumentPosition&&d.compareDocumentPosition(c)&16));return a?!1:!0}function Yb(a,c,d){if(a){var f=F.findParentContentNode(a);if(f&&zb(f,a)&&(a=F.buildContentBlock(f)))return!a.target&&d&&(a.target=
d),F.buildInteractionRequestParams(c,a.name,a.piece,a.target)}}function Zb(a){if(!za||!za.length)return!1;var c,d;for(c=0;c<za.length;c++)if((d=za[c])&&d.name===a.name&&d.piece===a.piece&&d.target===a.target)return!0;return!1}function Ab(a){if(!a)return!1;var c=F.findTargetNode(a);if(!c||F.shouldIgnoreInteraction(c))return!1;var d=yb(c);if(Bb&&d&&d.type)return!1;if(t.isLinkElement(c)&&t.hasNodeAttributeWithValue(c,"href")){d=String(t.getAttributeValueFromNode(c,"href"));if(0===d.indexOf("#"))return!1;
if(Ua(d))return!0;if(!F.isUrlToCurrentDomain(d))return!1;var f=F.buildContentBlock(a);if(!f)return;a=f.name;var n=f.piece;f=f.target;if(!t.hasNodeAttributeWithValue(c,F.CONTENT_TARGET_ATTR)||c.wasContentTargetAttrReplaced)c.wasContentTargetAttrReplaced=!0,f=F.toAbsoluteUrl(d),t.setAnyAttribute(c,F.CONTENT_TARGET_ATTR,f);d=Xb(d,"click",a,n,f);F.setHrefAttribute(c,d);return!0}return!1}function $b(a){return function(c){if(a){var d=F.findParentContentNode(a),f;c&&(f=c.target||c.srcElement);f||(f=a);if(zb(d,
f)){Y(V);t.isLinkElement(a)&&t.hasNodeAttributeWithValue(a,"href")&&t.hasNodeAttributeWithValue(a,F.CONTENT_TARGET_ATTR)&&(c=t.getAttributeValueFromNode(a,"href"),!Ua(c)&&a.wasContentTargetAttrReplaced&&t.setAnyAttribute(a,F.CONTENT_TARGET_ATTR,""));c=yb(a);if(db&&c&&c.type)return c.type;if(Ab(d))return"href";if(d=F.buildContentBlock(d))return d=Va("click",d.name,d.piece,d.target),D(d,V),d}}}}function ac(a){if(a&&a.length){var c,d;for(c=0;c<a.length;c++)(d=F.findTargetNode(a[c]))&&!d.contentInteractionTrackingSetupDone&&
(d.contentInteractionTrackingSetupDone=!0,B(d,"click",$b(d)))}}function bc(a,c){if(!a||!a.length)return[];var d;for(d=0;d<a.length;d++)Zb(a[d])?(a.splice(d,1),d--):za.push(a[d]);if(!a||!a.length)return[];if(c&&c.length)for(d=0;d<c.length;d++)Ab(c[d]);ac(c);var f=[];for(d=0;d<a.length;d++)c=oa(F.buildImpressionRequestParams(a[d].name,a[d].piece,a[d].target),void 0,"contentImpressions"),f.push(c);return f}function eb(a){var c=F.collectContent(a);return bc(c,a)}function Cb(a){if(!a||!a.length)return[];
var c;for(c=0;c<a.length;c++)F.isNodeVisible(a[c])||(a.splice(c,1),c--);return a&&a.length?eb(a):[]}function cc(a,c,d){a=F.buildImpressionRequestParams(a,c,d);return oa(a,null,"contentImpression")}function dc(a,c){if(a&&(a=F.findParentContentNode(a),a=F.buildContentBlock(a)))return c||(c="Unknown"),Va(c,a.name,a.piece,a.target)}function ec(a,c,d,f,n){if(0===String(a).length||0===String(c).length)return!1;a="e_c="+C(a)+"&e_a="+C(c)+(h(d)?"&e_n="+C(d):"")+(h(f)?"&e_v="+C(f):"");n=oa(a,n,"event");D(n,
V)}function fc(a,c,d,f,n){c=c+"="+C(q(a));(a=Yb(n,"click",a))&&(c+="&"+a);d=oa(c,d,"link");D(d,f?0:V,f)}function gc(a,c){return""!==a?a+c.charAt(0).toUpperCase()+c.slice(1):c}function ia(a){var c,d,f=["","webkit","ms","moz"];if(!hc)for(d=0;d<f.length;d++){var n=f[d];if(Object.prototype.hasOwnProperty.call(v,gc(n,"hidden"))){"prerender"===v[gc(n,"visibilityState")]&&(c=!0);break}}c?B(v,n+"visibilitychange",function x(){v.removeEventListener(n+"visibilitychange",x,!1);a()}):a()}function fb(a){"complete"===
v.readyState?a():w.addEventListener?w.addEventListener("load",a):w.attachEvent&&w.attachEvent("onLoad",a)}function Db(a){(v.attachEvent?"complete"===v.readyState:"loading"!==v.readyState)?a():v.addEventListener?v.addEventListener("DOMContentLoaded",a):v.attachEvent&&v.attachEvent("onreadystatechange",a)}function ic(a){var c=yb(a);c&&c.type&&(c.href=l(c.href),fc(c.href,c.type,void 0,null,a))}function Eb(a){a=a||w.event;var c=a.which||a.button;var d=a.target||a.srcElement;"click"===a.type?d&&ic(d):
"mousedown"===a.type?1!==c&&2!==c||!d?gb=hb=null:(gb=c,hb=d):"mouseup"===a.type&&(c===gb&&d===hb&&ic(d),gb=hb=null)}function jc(a,c){c?(B(a,"mouseup",Eb,!1),B(a,"mousedown",Eb,!1)):B(a,"click",Eb,!1)}function kc(a){if(!db){db=!0;var c,d=xb(lc,"ignore"),f=v.links;if(f)for(c=0;c<f.length;c++)d.test(f[c].className)||jc(f[c],a)}}function mc(a,c,d){function f(){n=!0}if(La)return!0;La=!0;var n=!1,r,x;fb(function(){function L(J){setTimeout(function(){La&&(n=!1,d.trackVisibleContentImpressions(),L(J))},J)}
function E(J){setTimeout(function(){La&&(n&&(n=!1,d.trackVisibleContentImpressions()),E(J))},J)}if(a){r=["scroll","resize"];for(x=0;x<r.length;x++)v.addEventListener?v.addEventListener(r[x],f):w.attachEvent("on"+r[x],f);E(100)}c&&0<c&&(c=parseInt(c,10),L(c))})}function Ha(a){if("undefined"!=typeof _paq&&null!=_paq&&0<_paq.length){var c=null;_paq.forEach(function(d){d[0]===a&&(c=2==d.length?d[1]:d[0])});return c}return null}var ib={},Fb=S(v.domain,w.location.href,Ga()),ob=z(Fb[0]),Pb=l(Fb[1]),Ea=l(Fb[2]),
nc=!1,Lb="GET",Kb="application/x-www-form-urlencoded; charset=UTF-8",ha=b||"",oc="",ub="",W=e||"",Ja="",Qa="",ab,Tb=v.title,ya="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),Ya=[ob],lc=[],Vb=[],Wb=[],V=500,wb,Ta,Jb,xa,bb=["pk_campaign",
"piwik_campaign","utm_campaign","utm_source","utm_medium"],cb=["pk_kwd","piwik_kwd","utm_term"],mb="daxtr",Da,wa,va=!1,Za,hc,rb,Gb=339552E5,qb=18E5,Rb=!0,tb=0,Qb=!1,da=!1,vb,Fa={},sb={},aa={},qa={},za=[],La=!1,Ia=!1,db=!1,Bb=!1,Ub=!1,pb,gb,hb,nb=H,Mb;(function(){var a,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",
ag:"application/x-silverlight"},d=/Mac OS X.*Safari\//.test(ca.userAgent)?w.devicePixelRatio||1:1;if(!/MSIE/.test(ca.userAgent)){if(ca.mimeTypes&&ca.mimeTypes.length)for(a in c)if(Object.prototype.hasOwnProperty.call(c,a)){var f=ca.mimeTypes[c[a]];qa[a]=f&&f.enabledPlugin?"1":"0"}"unknown"!==typeof navigator.javaEnabled&&h(ca.javaEnabled)&&ca.javaEnabled()&&(qa.java="1");m(w.GearsFactory)&&(qa.gears="1");qa.cookie=U()}qa.res=pc.width*d+"x"+pc.height*d})();R();ta();ka("run",function(a,c){var d=null;
if(p(a)&&!h(ib[a])&&c){if(u(c))d=c;else if(p(c))try{eval("hookObj ="+c)}catch(f){}ib[a]=d}return d});return{hook:ib,getHook:function(a){return ib[a]},getQuery:function(){return t},getContent:function(){return F},buildContentImpressionRequest:cc,buildContentInteractionRequest:Va,buildContentInteractionRequestNode:dc,buildContentInteractionTrackingRedirectUrl:Xb,getContentImpressionsRequestsFromNodes:eb,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:Cb,trackCallbackOnLoad:fb,trackCallbackOnReady:Db,
buildContentImpressionsRequests:bc,wasContentImpressionAlreadyTracked:Zb,appendContentInteractionToRequestIfPossible:Yb,setupInteractionsTracking:ac,trackContentImpressionClickInteraction:$b,internalIsNodeVisible:Ma,isNodeAuthorizedToTriggerInteraction:zb,replaceHrefIfInternalLink:Ab,getConfigDownloadExtensions:function(){return ya},enableTrackOnlyVisibleContent:function(a,c){return mc(a,c,this)},clearTrackedContentImpressions:function(){za=[]},getTrackedContentImpressions:function(){return za},clearEnableTrackOnlyVisibleContent:function(){La=
!1},disableLinkTracking:function(){Bb=db=!1},getConfigVisitorCookieTimeout:function(){return Gb},getRemainingVisitorCookieTimeout:function(){var a=(new Date).getTime(),c=la().createTs;return 1E3*parseInt(c,10)+Gb-a},afterAuthFlg:function(a){},trackingType:function(a){if((1==a||2==a)&&"function"===typeof dcmganCallback){a=dcmganCallback;var c={};c.uid=la().uuid;a(c)}},daReqProb:function(a){},gaCallbackTimeout:function(a){clearTimeout(a)},getVisitorId:function(){return la().uuid},getVisitorInfo:function(){return Aa()},
getAttributionInfo:function(){return ua()},getAttributionCampaignName:function(){return ua()[0]},getAttributionCampaignKeyword:function(){return ua()[1]},getAttributionReferrerTimestamp:function(){return ua()[2]},getAttributionReferrerUrl:function(){return ua()[3]},setTrackerUrl:function(a){ha=a},getTrackerUrl:function(){return ha},getSiteId:function(){return W},setSiteId:function(a){W=a;ta()},setUserId:function(a){h(a)&&a.length&&(Ja=a,Qa=nb(Ja).substr(0,32))},getUserId:function(){return Ja},setCustomData:function(a,
c){u(a)?xa=a:(xa||(xa={}),xa[a]=c)},getCustomData:function(){return xa},setCustomRequestProcessing:function(a){vb=a},appendToTrackingUrl:function(a){ub=a},getRequest:function(a){return oa(a)},addPlugin:function(a,c){Na[a]=c},setCustomVariable:function(a,c,d,f){h(f)||(f="visit");h(c)&&(h(d)||(d=""),0<a&&(c=p(c)?c:String(c),d=p(d)?d:String(d),c=[c.slice(0,200),d.slice(0,200)],"visit"===f||2===f?(!1===da&&(da=fa()),da[a]=c):"page"===f||3===f?Fa[a]=c:"event"===f&&(sb[a]=c)))},getCustomVariable:function(a,
c){h(c)||(c="visit");if("page"===c||3===c)var d=Fa[a];else if("event"===c)d=sb[a];else if("visit"===c||2===c)!1===da&&(da=fa()),d=da[a];return!h(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,c){this.getCustomVariable(a,c)&&this.setCustomVariable(a,"","",c)},storeCustomVariablesInCookie:function(){Qb=!0},setLinkTrackingTimer:function(a){V=a},setDownloadExtensions:function(a){p(a)&&(a=a.split("|"));ya=a},addDownloadExtensions:function(a){var c;p(a)&&(a=a.split("|"));for(c=0;c<a.length;c++)ya.push(a[c])},
removeDownloadExtensions:function(a){var c,d=[];p(a)&&(a=a.split("|"));for(c=0;c<ya.length;c++)-1===M(a,ya[c])&&d.push(ya[c]);ya=d},setDomains:function(a){Ya=p(a)?[a]:a;Ya.push(ob)},setIgnoreClasses:function(a){lc=p(a)?[a]:a},setRequestMethod:function(a){Lb=a||"GET"},setRequestContentType:function(a){Kb=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){Ea=a},setCustomUrl:function(a){var c=Pb;if(Wa(a))ab=a;else if("/"===a.slice(0,1))ab=Wa(c)+"://"+X(c)+a;else{c=q(c);
var d=c.indexOf("?");0<=d&&(c=c.slice(0,d));d=c.lastIndexOf("/");d!==c.length-1&&(c=c.slice(0,d+1));ab=c+a}},setDocumentTitle:function(a){Tb=a},setAPIUrl:function(a){oc=a},setDownloadClasses:function(a){Vb=p(a)?[a]:a},setLinkClasses:function(a){Wb=p(a)?[a]:a},setCampaignNameKey:function(a){bb=p(a)?[a]:a},setCampaignKeywordKey:function(a){cb=p(a)?[a]:a},discardHashTag:function(a){Jb=a},setCookieNamePrefix:function(a){mb=a;da=fa()},setCookieDomain:function(a){a=z(a);g("test","testvalue",1E4,null,a);
if("testvalue"===k("test")){g("test","",-86400,null,a);var c=!0}else c=!1;c&&(Da=a,R())},setCookiePath:function(a){wa=a;R()},setVisitorCookieTimeout:function(a){Gb=1E3*a},setSessionCookieTimeout:function(a){qb=1E3*a},setReferralCookieTimeout:function(a){},setConversionAttributionFirstReferrer:function(a){rb=a},disableCookies:function(){va=!0;qa.cookie="0"},deleteCookies:function(){Nb()},setDoNotTrack:function(a){var c=ca.doNotTrack||ca.msDoNotTrack;(Za=a&&("yes"===c||"1"===c))&&this.disableCookies()},
addListener:function(a,c){jc(a,c)},enableLinkTracking:function(a){Bb=!0;Oa?kc(a):lb.push(function(){kc(a)})},enableJSErrorTracking:function(){if(!nc){nc=!0;var a=w.onerror;w.onerror=function(c,d,f,n,r){ia(function(){var x=d+":"+f;n&&(x+=":"+n);ec("JavaScript Errors",x,c)});return a?a(c,d,f,n,r):!1}}},disablePerformanceTracking:function(){Rb=!1},setGenerationTimeMs:function(a){tb=parseInt(a,10)},setHeartBeatTimer:function(a,c){wb=(new Date).getTime()+1E3*a;Ta=1E3*c},killFrame:function(){w.location!==
w.top.location&&(w.top.location=w.location)},redirectFile:function(a){"file:"===w.location.protocol&&(w.location=a)},setCountPreRendered:function(a){hc=a},trackGoal:function(a,c,d){ia(function(){var f=oa("idgoal="+a+(c?"&revenue="+c:""),d,"goal");D(f,V)})},trackLink:function(a,c,d,f){ia(function(){fc(a,c,d,f)})},trackPageView:function(a,c){za=[];Ba(W)?ia(function(){tc(ha,oc,W)}):ia(function(){vc(a,c)})},trackAllContentImpressions:function(){Ba(W)||ia(function(){Db(function(){var a=F.findContentNodes();
a=eb(a);A(a,V)})})},trackVisibleContentImpressions:function(a,c){Ba(W)||(h(a)||(a=!0),h(c)||(c=750),mc(a,c,this),ia(function(){fb(function(){var d=F.findContentNodes();d=Cb(d);A(d,V)})}))},trackContentImpression:function(a,c,d){!Ba(W)&&a&&(c=c||"Unknown",ia(function(){var f=cc(a,c,d);D(f,V)}))},trackContentImpressionsWithinNode:function(a){!Ba(W)&&a&&ia(function(){La?fb(function(){var c=F.findContentNodesWithinNode(a);c=Cb(c);A(c,V)}):Db(function(){var c=F.findContentNodesWithinNode(a);c=eb(c);A(c,
V)})})},trackContentInteraction:function(a,c,d,f){!Ba(W)&&a&&c&&(d=d||"Unknown",ia(function(){var n=Va(a,c,d,f);D(n,V)}))},trackContentInteractionNode:function(a,c){!Ba(W)&&a&&ia(function(){var d=dc(a,c);D(d,V)})},trackEvent:function(a,c,d,f){ia(function(){ec(a,c,d,f)})},trackSiteSearch:function(a,c,d){ia(function(){var f=oa("search="+C(a)+(c?"&search_cat="+C(c):"")+(h(d)?"&search_count="+d:""),void 0,"sitesearch");D(f,V)})},setEcommerceView:function(a,c,d,f){h(d)&&d.length?d instanceof Array&&(d=
JSON2.stringify(d)):d="";Fa[5]=["_pkc",d];h(f)&&String(f).length&&(Fa[2]=["_pkp",f]);if(h(a)&&a.length||h(c)&&c.length)h(a)&&a.length&&(Fa[3]=["_pks",a]),h(c)&&c.length||(c=""),Fa[4]=["_pkn",c]},addEcommerceItem:function(a,c,d,f,n){a.length&&(aa[a]=[a,c,d,f,n])},trackEcommerceOrder:function(a,c,d,f,n,r){String(a).length&&h(c)&&Sb(a,c,d,f,n,r)},trackEcommerceCartUpdate:function(a){h(a)&&Sb("",a,"","","","")},diPiNK:function(a){},diPiNK2:function(a){if(1!=k("dcmdipink")){var c=[];if(""!=document.cookie){a=
document.cookie.split("; ");for(var d=0;d<a.length;d++){var f=a[d].split("=");c[f[0]]=decodeURIComponent(f[1])}}d=document;a=d.createElement("script");d=d.getElementsByTagName("script")[0];a.async=!0;a.src="https://dmp.im-apps.net/scripts/im-uid-hook.js?cid=6094";d.parentNode.insertBefore(a,d);if(""!=document.cookie)for(a=document.cookie.split("; "),d=0;d<a.length;d++)f=a[d].split("="),c[f[0]]=decodeURIComponent(f[1]);setTimeout(function(){if(""!=document.cookie)for(var n=document.cookie.split("; "),
r=0;r<n.length;r++){var x=n[r].split("=");c[x[0]]=decodeURIComponent(x[1])}n=k("daxtr");r=c["_im_uid.6094"];n&&r&&(n=n.split(".")[0],n="https://b6.im-apps.net/6094/map/"+r+"/"+n,r=document.createElement("img"),r.src=n,r.style.display="none",r.style.width="1px",r.style.height="1px",document.body.appendChild(r),n=(new Date).getTime(),n=(new Date(n+864E5)).toGMTString(),n="dcmdipink="+escape(1)+"; expires="+n+"; path=/",document.cookie=n)},500)}},dcmsyfl:function(a){},dcmsydc:function(a){},dcmsyal:function(a){},
dcmsyhk:function(a){if(window.navigator.cookieEnabled&&!(1==k("dcmsyhk")||null==a||0>=a||0!=(new Date).getTime()%a)&&(a=k("daxtr"))){a=a.split(".")[0];var c=-1<ha.indexOf("dmc-t")?"//sy.dcm-analytics.com":"//sy.docomo-analytics.com";a="?oid=207d81ffda0cc019&rdr="+C(c+"/dcm/sy/hk/?idsite="+(W+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+a+"&uid={AONEID}"));c=document.createElement("img");c.setAttribute("src","//aw.dw.impact-ad.jp/c/u/"+a);c.style.display="none";document.body.appendChild(c);
g("dcmsyhk","1",2592E6,"/")}},dcmsytd:function(a){},dcmsyyh:function(a){},dcmsyde:function(a){if(window.navigator.cookieEnabled&&!(1==k("dcmsyde")||null==a||0>=a||0!=(new Date).getTime()%a)&&(a=k("daxtr"))){a=a.split(".")[0];var c="idsite="+W,d="url="+C(document.location.protocol+"//"+document.domain);a="?p_id=docomo&"+c+"&"+d+"&dauid="+a+"&companyid=11";c=document.createElement("img");c.setAttribute("src","//pp.d2-apps.net/v1/redirect"+a);c.style.display="none";document.body.appendChild(c);g("dcmsyde",
"1",864E5,"/")}},cvv:function(a){var c=(-1<ha.indexOf("dmc-t.docomo.ne.jp")?"//devcv.dmc-t.docomo.ne.jp":"//cv.dmc.docomo.ne.jp")+"/dcm/coll/cv/";k("daxtr")&&(a+="&dauid="+k("daxtr").split(".")[0]);var d=document.createElement("img");d.setAttribute("src",c+(-1<a.indexOf("?")?a:"?"+a));d.style.display="none";document.body.appendChild(d)},cvc:function(a,c){var d=(-1<ha.indexOf("dmc-t.docomo.ne.jp")?"//devcv.dmc-t.docomo.ne.jp":"//cv.dmc.docomo.ne.jp")+"/dcm/coll/cv/",f=document.getElementById(a);if(f){k("daxtr")&&
(c+="&dauid="+k("daxtr").split(".")[0]);var n=f.href;f.onclick=function(r){c=c.replace(/&dcm_z=[0-9]{13}/,"");c+="&dcm_z="+(new Date).getTime();var x=new XMLHttpRequest,L=r.button;r.which||void 0===L||(r.which=L&1?1:L&2?3:L&4?2:0);if(!(0!==r.button&&1!==r.which||r.altKey||r.ctrlKey||r.shiftKey||r.metaKey||"_blank"==f.target||"_new"==f.target)){r.preventDefault();x.onreadystatechange=function(){2==x.readyState&&(null!=E&&(clearTimeout(E),E=null),window.location.href=n)};var E=setTimeout(function(){window.location.href=
n},1E3)}x.open("GET",d+(-1<c.indexOf("?")?c:"?"+c));x.withCredentials=!0;x.send()}}}}}var Pa,Na={},v=document,ca=navigator,pc=screen,w=window,Ka=w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance,Oa=!1,lb=[],C=w.encodeURIComponent,kb=w.decodeURIComponent,rc=unescape,pa,t={htmlCollectionToArray:function(b){var e=[],g;if(!b||!b.length)return e;for(g=0;g<b.length;g++)e.push(b[g]);return e},find:function(b){if(!document.querySelectorAll||!b)return[];b=document.querySelectorAll(b);return this.htmlCollectionToArray(b)},
findMultiple:function(b){if(!b||!b.length)return[];var e,g=[];for(e=0;e<b.length;e++){var k=this.find(b[e]);g=g.concat(k)}return g=this.makeNodesUnique(g)},findNodesByTagName:function(b,e){if(!b||!e||!b.getElementsByTagName)return[];b=b.getElementsByTagName(e);return this.htmlCollectionToArray(b)},makeNodesUnique:function(b){var e=[].concat(b);b.sort(function(N,O){if(N===O)return 0;N=M(e,N);O=M(e,O);return N===O?0:N>O?-1:1});if(1>=b.length)return b;var g=0,k=0,q=[],P;for(P=b[g++];P;)P===b[g]&&(k=
q.push(g)),P=b[g++]||null;for(;k--;)b.splice(q[k],1);return b},getAttributeValueFromNode:function(b,e){if(this.hasNodeAttribute(b,e)){if(b&&b.getAttribute)return b.getAttribute(e);if(b&&b.attributes&&"undefined"!==typeof b.attributes[e]){if(b.attributes[e].value)return b.attributes[e].value;if(b.attributes[e].nodeValue)return b.attributes[e].nodeValue;var g=b.attributes;if(g){for(b=0;b<g.length;b++)if(g[b].nodeName===e)return g[b].nodeValue;return null}}}},hasNodeAttributeWithValue:function(b,e){return!!this.getAttributeValueFromNode(b,
e)},hasNodeAttribute:function(b,e){return b&&b.hasAttribute?b.hasAttribute(e):b&&b.attributes?"undefined"!==typeof b.attributes[e]:!1},hasNodeCssClass:function(b,e){return b&&e&&b.className&&(b=b.className.split(" "),-1!==M(b,e))?!0:!1},findNodesHavingAttribute:function(b,e,g){g||(g=[]);if(!b||!e)return g;b=Q(b);if(!b||!b.length)return g;var k;for(k=0;k<b.length;k++){var q=b[k];this.hasNodeAttribute(q,e)&&g.push(q);g=this.findNodesHavingAttribute(q,e,g)}return g},findFirstNodeHavingAttribute:function(b,
e){if(b&&e){if(this.hasNodeAttribute(b,e))return b;if((b=this.findNodesHavingAttribute(b,e))&&b.length)return b[0]}},findFirstNodeHavingAttributeWithValue:function(b,e){if(b&&e){if(this.hasNodeAttributeWithValue(b,e))return b;if((b=this.findNodesHavingAttribute(b,e))&&b.length){var g;for(g=0;g<b.length;g++)if(this.getAttributeValueFromNode(b[g],e))return b[g]}}},findNodesHavingCssClass:function(b,e,g){g||(g=[]);if(!b||!e)return g;if(b.getElementsByClassName)return e=b.getElementsByClassName(e),this.htmlCollectionToArray(e);
b=Q(b);if(!b||!b.length)return[];var k;for(k=0;k<b.length;k++){var q=b[k];this.hasNodeCssClass(q,e)&&g.push(q);g=this.findNodesHavingCssClass(q,e,g)}return g},findFirstNodeHavingClass:function(b,e){if(b&&e){if(this.hasNodeCssClass(b,e))return b;if((b=this.findNodesHavingCssClass(b,e))&&b.length)return b[0]}},isLinkElement:function(b){if(!b)return!1;b=String(b.nodeName).toLowerCase();return-1!==M(["a","area"],b)},setAnyAttribute:function(b,e,g){b&&e&&(b.setAttribute?b.setAttribute(e,g):b[e]=g)}},F=
{CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return t.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+
"]"])},findContentNodesWithinNode:function(b){if(!b)return[];var e=t.findNodesHavingCssClass(b,this.CONTENT_CLASS),g=t.findNodesHavingAttribute(b,this.CONTENT_ATTR);if(g&&g.length){var k;for(k=0;k<g.length;k++)e.push(g[k])}t.hasNodeAttribute(b,this.CONTENT_ATTR)?e.push(b):t.hasNodeCssClass(b,this.CONTENT_CLASS)&&e.push(b);return e=t.makeNodesUnique(e)},findParentContentNode:function(b){if(b)for(var e=0;b&&b!==v&&b.parentNode;){if(t.hasNodeAttribute(b,this.CONTENT_ATTR)||t.hasNodeCssClass(b,this.CONTENT_CLASS))return b;
b=b.parentNode;if(1E3<e)break;e++}},findPieceNode:function(b){var e;(e=t.findFirstNodeHavingAttribute(b,this.CONTENT_PIECE_ATTR))||(e=t.findFirstNodeHavingClass(b,this.CONTENT_PIECE_CLASS));return e?e:b},findTargetNodeNoDefault:function(b){if(b){var e=t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_TARGET_ATTR);if(e||(e=t.findFirstNodeHavingAttribute(b,this.CONTENT_TARGET_ATTR))||(e=t.findFirstNodeHavingClass(b,this.CONTENT_TARGET_CLASS)))return e}},findTargetNode:function(b){var e=this.findTargetNodeNoDefault(b);
return e?e:b},findContentName:function(b){if(b){var e=t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_NAME_ATTR);if(e)return t.getAttributeValueFromNode(e,this.CONTENT_NAME_ATTR);if(e=this.findContentPiece(b))return this.removeDomainIfIsInLink(e);if(t.hasNodeAttributeWithValue(b,"title"))return t.getAttributeValueFromNode(b,"title");e=this.findPieceNode(b);if(t.hasNodeAttributeWithValue(e,"title"))return t.getAttributeValueFromNode(e,"title");b=this.findTargetNode(b);if(t.hasNodeAttributeWithValue(b,
"title"))return t.getAttributeValueFromNode(b,"title")}},findContentPiece:function(b){if(b){var e=t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_PIECE_ATTR);if(e)return t.getAttributeValueFromNode(e,this.CONTENT_PIECE_ATTR);b=this.findPieceNode(b);if(b=this.findMediaUrlInNode(b))return this.toAbsoluteUrl(b)}},findContentTarget:function(b){if(b){var e=this.findTargetNode(b);if(t.hasNodeAttributeWithValue(e,this.CONTENT_TARGET_ATTR))return t.getAttributeValueFromNode(e,this.CONTENT_TARGET_ATTR);
if(t.hasNodeAttributeWithValue(e,"href"))return b=t.getAttributeValueFromNode(e,"href"),this.toAbsoluteUrl(b);b=this.findPieceNode(b);if(t.hasNodeAttributeWithValue(b,"href"))return b=t.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(b)}},isSameDomain:function(b){if(!b||!b.indexOf)return!1;if(0===b.indexOf(this.getLocation().origin))return!0;b=b.indexOf(this.getLocation().host);return 8>=b&&0<=b?!0:!1},removeDomainIfIsInLink:function(b){b&&b.search&&-1!==b.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(b)&&
((b=b.replace(/^.*\/\/[^/]+/,""))||(b="/"));return b},findMediaUrlInNode:function(b){if(b){var e=b.nodeName.toLowerCase();if(-1!==M(["img","embed","video","audio"],e)&&t.findFirstNodeHavingAttributeWithValue(b,"src"))return b=t.findFirstNodeHavingAttributeWithValue(b,"src"),t.getAttributeValueFromNode(b,"src");if("object"===e&&t.hasNodeAttributeWithValue(b,"data"))return t.getAttributeValueFromNode(b,"data");if("object"===e){if((e=t.findNodesByTagName(b,"param"))&&e.length){var g;for(g=0;g<e.length;g++)if("movie"===
t.getAttributeValueFromNode(e[g],"name")&&t.hasNodeAttributeWithValue(e[g],"value"))return t.getAttributeValueFromNode(e[g],"value")}if((b=t.findNodesByTagName(b,"embed"))&&b.length)return this.findMediaUrlInNode(b[0])}}},trim:function(b){return b&&String(b)===b?b.replace(/^\s+|\s+$/g,""):b},isOrWasNodeInViewport:function(b){if(!b||!b.getBoundingClientRect||1!==b.nodeType)return!0;var e=b.getBoundingClientRect(),g=v.documentElement||{},k=0>e.top;k&&b.offsetTop&&(k=0<b.offsetTop+e.height);b=g.clientWidth;
w.innerWidth&&b>w.innerWidth&&(b=w.innerWidth);g=g.clientHeight;w.innerHeight&&g>w.innerHeight&&(g=w.innerHeight);return(0<e.bottom||k)&&0<e.right&&e.left<b&&(e.top<g||k)},isNodeVisible:function(b){var e=Ma(b);b=this.isOrWasNodeInViewport(b);return e&&b},buildInteractionRequestParams:function(b,e,g,k){var q="";b&&(q+="c_i="+C(b));e&&(q&&(q+="&"),q+="c_n="+C(e));g&&(q&&(q+="&"),q+="c_p="+C(g));k&&(q&&(q+="&"),q+="c_t="+C(k));return q},buildImpressionRequestParams:function(b,e,g){b="c_n="+C(b)+"&c_p="+
C(e);g&&(b+="&c_t="+C(g));return b},buildContentBlock:function(b){if(b){var e=this.findContentName(b),g=this.findContentPiece(b);b=this.findContentTarget(b);e=this.trim(e);g=this.trim(g);b=this.trim(b);return{name:e||"Unknown",piece:g||"Unknown",target:b||""}}},collectContent:function(b){if(!b||!b.length)return[];var e=[],g;for(g=0;g<b.length;g++){var k=this.buildContentBlock(b[g]);h(k)&&e.push(k)}return e},setLocation:function(b){this.location=b},getLocation:function(){var b=this.location||w.location;
b.origin||(b.origin=b.protocol+"//"+b.hostname+(b.port?":"+b.port:""));return b},toAbsoluteUrl:function(b){return b&&String(b)===b||""===b?""===b?this.getLocation().href:-1!==b.search(/^\/\//)?this.getLocation().protocol+b:-1!==b.search(/:\/\//)?b:0===b.indexOf("#")||0===b.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+b:0===b.search("^[a-zA-Z]{2,11}:")?b:-1!==b.search(/^\//)?this.getLocation().origin+b:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+b:
b},isUrlToCurrentDomain:function(b){b=this.toAbsoluteUrl(b);if(!b)return!1;var e=this.getLocation().origin;return e===b?!0:0===String(b).indexOf(e)?":"===String(b).substr(e.length,1)?!1:!0:!1},setHrefAttribute:function(b,e){b&&e&&t.setAnyAttribute(b,"href",e)},shouldIgnoreInteraction:function(b){var e=t.hasNodeAttribute(b,this.CONTENT_IGNOREINTERACTION_ATTR);b=t.hasNodeCssClass(b,this.CONTENT_IGNOREINTERACTION_CLASS);return e||b}};B(w,"beforeunload",function(){ka("unload");if(Pa){do var b=new Date;
while(b.getTimeAlias()<Pa)}},!1);(function(){var b;v.addEventListener?B(v,"DOMContentLoaded",function g(){v.removeEventListener("DOMContentLoaded",g,!1);ja()}):v.attachEvent&&(v.attachEvent("onreadystatechange",function g(){"complete"===v.readyState&&(v.detachEvent("onreadystatechange",g),ja())}),v.documentElement.doScroll&&w===w.top&&function k(){if(!Oa){try{v.documentElement.doScroll("left")}catch(q){setTimeout(k,0);return}ja()}}());/WebKit/.test(ca.userAgent)&&(b=setInterval(function(){if(Oa||
/loaded|complete/.test(v.readyState))clearInterval(b),ja()},10));B(w,"load",ja,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;var Xa=new Ib;var Hb={setTrackerUrl:1,setAPIUrl:1,setUserId:1,setSiteId:1,disableCookies:1,enableLinkTracking:1};for(pa=0;pa<_paq.length;pa++){var jb=_paq[pa][0];Hb[jb]&&(G(_paq[pa]),delete _paq[pa],1<Hb[jb]&&void 0!==console&&console&&console.error&&console.error("The method "+jb+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),
Hb[jb]++)}for(pa=0;pa<_paq.length;pa++)_paq[pa]&&G(_paq[pa]);_paq=new function(){return{push:G}};var qc={addPlugin:function(b,e){Na[b]=e},getTracker:function(b,e){h(e)||(e=this.getAsyncTracker().getSiteId());h(b)||(b=this.getAsyncTracker().getTrackerUrl());return new Ib(b,e)},getAsyncTracker:function(){return Xa}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return qc});return qc}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();
(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
"function"!==typeof piwik_log&&(piwik_log=function(l,h,m,u){function p(B){try{return eval("piwik_"+B)}catch(ka){}}var G=Piwik.getTracker(m,h);G.setDocumentTitle(l);G.setCustomData(u);(l=p("tracker_pause"))&&G.setLinkTrackingTimer(l);(l=p("download_extensions"))&&G.setDownloadExtensions(l);(l=p("hosts_alias"))&&G.setDomains(l);(l=p("ignore_classes"))&&G.setIgnoreClasses(l);G.trackPageView();p("install_tracker")&&(piwik_track=function(B,ka,ja,T){G.setSiteId(ka);G.setTrackerUrl(ja);G.trackLink(B,T)},
G.enableLinkTracking())});
